// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_HYtYKrBXqkh6YFyekpO_gibXVoeRoQ',
    appId: '1:565405440968:web:980ecee0fffdee0b3a7efd',
    messagingSenderId: '565405440968',
    projectId: 'service-app-86f57',
    authDomain: 'service-app-86f57.firebaseapp.com',
    storageBucket: 'service-app-86f57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAAMW9QjM4Nt_lXghTUpTod-Z1HMDXbfQ',
    appId: '1:565405440968:android:248c99f0e39e51863a7efd',
    messagingSenderId: '565405440968',
    projectId: 'service-app-86f57',
    storageBucket: 'service-app-86f57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkEgUEbY9feGftPhKZEpL888eELX0zcoA',
    appId: '1:565405440968:ios:b1122224a395539f3a7efd',
    messagingSenderId: '565405440968',
    projectId: 'service-app-86f57',
    storageBucket: 'service-app-86f57.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkEgUEbY9feGftPhKZEpL888eELX0zcoA',
    appId: '1:565405440968:ios:b1122224a395539f3a7efd',
    messagingSenderId: '565405440968',
    projectId: 'service-app-86f57',
    storageBucket: 'service-app-86f57.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF_HYtYKrBXqkh6YFyekpO_gibXVoeRoQ',
    appId: '1:565405440968:web:eb94085e381e7b363a7efd',
    messagingSenderId: '565405440968',
    projectId: 'service-app-86f57',
    authDomain: 'service-app-86f57.firebaseapp.com',
    storageBucket: 'service-app-86f57.firebasestorage.app',
  );
}
